### PR TITLE
fix 11.0.2 errors

### PR DESCRIPTION
**Pull request by paidfire**
Fixes for 11.0.2 errors. 
Related to #168

### CODE REVIEW

**Comment by jjklee121** [comment]
Thanks for this fix 👍

**Comment by Kalanndok** [comment]
It didn't fix everything though I'm afraid.
Buffs/Debuffs don't display anymore with the target frame and ZPerl_Raid still throws the same errors with the missing function-qualification.

**Comment by paidfire** [comment]
> It didn't fix everything though I'm afraid. Buffs/Debuffs don't display anymore with the target frame and ZPerl_Raid still throws the same errors with the missing function-qualification.

I don't use ZPerl_Raid maybe that's why I didn't see any errors related to it.

**Comment by Kalanndok** [comment]
It's actually RaidFrames (I think) which is included in the package.
I don't have them active either, but it still showed the LUA errors.

**Comment by Kbz4** [comment]
ty for fix!

**Pull request closed without merging**
